# Generated by Django 5.0.6 on 2024-06-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_product_raw_materials_product_chocolate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vertical',
        ),
        migrations.AlterField(
            model_name='product',
            name='chocolate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='coffee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='flour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='milk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
