# Generated by Django 5.0.6 on 2024-06-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_sold_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='raw_materials',
        ),
        migrations.AddField(
            model_name='product',
            name='chocolate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='coffee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='flour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='milk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sugar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
