# Generated by Django 5.0.6 on 2024-06-24 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_product_vertical_alter_product_chocolate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chocolate',
            field=models.PositiveIntegerField(default=0, verbose_name='شکلات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='coffee',
            field=models.PositiveIntegerField(default=0, verbose_name='قهوه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flour',
            field=models.PositiveIntegerField(default=0, verbose_name='آرد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='milk',
            field=models.PositiveIntegerField(default=0, verbose_name='شیر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar',
            field=models.PositiveIntegerField(default=0, verbose_name='شکر'),
        ),
    ]
