# Generated by Django 5.0.6 on 2024-06-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_product_timeneeded'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hot_drinks', 'نوشیدنی گرم'), ('cold_drinks', 'نوشیدنی سرد'), ('cakes', 'کیک')], default='hot_drinks', max_length=20),
        ),
    ]
