# Generated by Django 5.0.6 on 2024-06-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hot_drinks', 'نوشیدنی گرم'), ('cold_drinks', 'نوشیدنی سرد'), ('cakes', 'کیک')], default='hot_drinks', max_length=20, verbose_name='دسته بندی محصول'),
        ),
    ]
